Django upgrades 2
sfbrigade/intentional-walk-server pull request #172
Opened 2023-08-31 00:54 UTC by benperlman

current error:

intentional-walk-server-server-1  | [OKAY] Loaded ENV .env File as KEY=VALUE Format
intentional-walk-server-server-1  | 12:50:09 AM client.1 |  > client@0.1.0 start
intentional-walk-server-server-1  | 12:50:09 AM client.1 |  > react-scripts start
intentional-walk-server-server-1  | 12:50:18 AM server.1 |  Watching for file changes with StatReloader
intentional-walk-server-server-1  | 12:50:40 AM client.1 |  Browserslist: caniuse-lite is outdated. Please run:
intentional-walk-server-server-1  | 12:50:40 AM client.1 |    npx update-browserslist-db@latest
intentional-walk-server-server-1  | 12:50:40 AM client.1 |    Why you should do it regularly: https://github.com/browserslist/update-db#readme
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  [HPM] Proxy created: /  -> http://localhost:8000
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  (node:51) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  (Use `node --trace-deprecation ...` to show where the warning was created)
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  (node:51) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  npm
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  ERR!
intentional-walk-server-server-1  | 12:50:44 AM client.1 |   Lifecycle script `start` failed with error: 
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  npm 
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  ERR!
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  Error: command failed
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  npm
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  ERR!
intentional-walk-server-server-1  | 12:50:44 AM client.1 |    in workspace: client@0.1.0
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  npm
intentional-walk-server-server-1  | 12:50:44 AM client.1 |  ERR!
intentional-walk-server-server-1  | 12:50:44 AM client.1 |    at location: /app/client
intentional-walk-server-server-1  | [DONE] Killing all processes with signal  SIGINT
intentional-walk-server-server-1  | 12:50:44 AM client.1 Exited with exit code null

2023-08-31 02:52 UTC, benperlman commented
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'intentional-walk-server@0.1.0',
npm WARN EBADENGINE   required: { node: '18.17.0', npm: '9.6.7' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '9.8.1' }
npm WARN EBADENGINE }

2023-09-06 19:14 UTC, benperlman commented
Passes test, some warnings about naive datetimes and other deprecated functions

2023-09-07 03:28 UTC, francisli requested changes
So, in our project setup, modifying the requirements.txt doesn't actually change anything- the requirements.txt is only used by the deployment process.

Rather, per the instructions at the end of the server README, the django package needs to be updated using the `poetry` package manager (from which we then export requirements.txt).

More info on poetry here: https://python-poetry.org/

2023-09-14 03:03 UTC, benperlman commented on home/tests/integration/views/api/utils.py
Modifying line 51 allowed these two tests to pass, otherwise it failed as ["3000-03-**02**T00:00:00", 3], != ["3000-03-**01**T00:00:00", 3],



  def test_get_home_users_daily(self):
        self.assertEqual(
            data,
            [
                ["Date", "Count"],
                ["3000-02-28T00:00:00", 0],
                ["3000-03-**02**T00:00:00", 3],
                ["3000-03-14T00:00:00", 0],        

 def test_get_home_users_cumulative(self):
        self.assertEqual(
            data,
            [
                ["Date", "Count"],
                ["3000-02-28T00:00:00", 0],
                ["3000-03-**02**T00:00:00", 3],
                ["3000-03-14T00:00:00", 3],

2023-09-14 03:06 UTC, benperlman commented on home/utils/__init__.py
This is used by the views user.py and data.py (as well as test cases) but had to be changed as "localize" caused an attribute not found error

2024-03-21 03:33 UTC, francisli commented
Closing, these changes were re-implemented by @markcerv in #175

2024-03-21 03:33 UTC, closed without merging