Histogram Model Frontend view - User Age histogram
sfbrigade/intentional-walk-server pull request #198
Opened 2024-03-31 16:23 UTC by odo-sfct

<img width="670" alt="image" src="https://github.com/sfbrigade/intentional-walk-server/assets/161795448/5e345e3e-a355-4fdd-b6b8-9541f23bd34c">

We could also generate other histograms for the other numeric data:
For intentional walks. We might be able to grab a `pg_dump` of the prod database, load it up and see what the distribution of walks are like for a given contest period.
<img width="561" alt="image" src="https://github.com/sfbrigade/intentional-walk-server/assets/161795448/9d5ad7ac-9b2d-47c8-8347-4919d5adf05f">

2024-04-11 01:47 UTC, francisli requested changes
This looks good to me, added one small comment...

Also, there are merge conflicts, can you resolve...?

2024-04-11 01:47 UTC, francisli commented on client/src/Home.js
> +              bin_custom="18,30,45,61"
In the Asana task, Danielle describes the buckets as:

```
Desired age groups: 18-29, 30-44, 45-59, 60+
```
So should the last bin_custom value just be 60...?

2024-04-13 16:56 UTC, odo-sfct commented
Thanks for the review!

Updated to match asana

<img width="668" alt="image" src="https://github.com/sfbrigade/intentional-walk-server/assets/161795448/446951a1-ae62-4bf2-98d9-c62d50a977ad">

2024-04-18 02:25 UTC, francisli approved these changes
lgtm!

2024-04-25 01:54 UTC, merged